Support writing with RangePartitioning (Issue #867)
GoogleCloudDataproc/spark-bigquery-connector pull request #1013
Opened 2023-07-07 09:39 UTC by vishalkarve15

2023-07-07 09:40 UTC, vishalkarve15 commented
/gcbrun

2023-07-07 09:45 UTC, vishalkarve15 commented
/gcbrun

2023-07-07 09:53 UTC, vishalkarve15 commented
/gcbrun

2023-07-07 20:41 UTC, davidrabinowitz commented on CHANGES.md
> +* Issue #867: Support writing with RangePartitioning
This line should be in the `Next` section

2023-07-10 07:40 UTC, vishalkarve15 commented
/gcbrun

2023-07-10 08:18 UTC, vishalkarve15 commented
/gcbrun

2023-07-10 10:06 UTC, vishalkarve15 commented
/gcbrun

2023-07-12 17:15 UTC, davidrabinowitz requested changes

2023-07-13 06:09 UTC, vishalkarve15 commented on spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java
> +    assertThat(readDF.count()).isEqualTo(3);
Done.

2023-07-13 06:09 UTC, vishalkarve15 commented
/gcbrun

2023-07-13 06:14 UTC, vishalkarve15 commented
/gcbrun

2023-07-17 07:48 UTC, vishalkarve15 commented
/gcbrun

2023-07-18 05:03 UTC, vishalkarve15 commented
/gcbrun

2023-07-19 09:06 UTC, vishalkarve15 commented
/gcbrun

2023-08-02 06:52 UTC, davidrabinowitz requested changes
Please update `README-template.md` with the new options, and explain the difference between date and range partitioning in the `Configuring Partitioning` section

2023-08-02 06:52 UTC, davidrabinowitz commented on bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
> +      rangePartitionBuilder.setField(options.getPartitionField().get());
nit:
```
options.getPartitionField().ifPresent(rangePartitionBuilder::setField);
options.getPartitionRange().ifPresent(rangePartitionBuilder::setRange);
```

2023-08-07 06:28 UTC, vishalkarve15 commented
/gcbrun

2023-08-08 02:03 UTC, davidrabinowitz approved these changes

2023-08-08 03:27 UTC, vishalkarve15 commented
/gcbrun

2023-08-08 05:40 UTC, merged