Issue #144: allow writing Spark Long to BQ TIME type
GoogleCloudDataproc/spark-bigquery-connector pull request #1017
Opened 2023-07-14 05:05 UTC by vishalkarve15

Currently, we allow reading BQ's TIME datatype into Spark's long datatype. However, writing Spark's long datatype into BQ's TIME datatype doesn't work.
This change adds that functionality.

2023-07-14 05:07 UTC, vishalkarve15 commented
/gcbrun

2023-07-14 05:18 UTC, vishalkarve15 commented
@davidrabinowitz do you think we should also allow writing strings to TIME? This will allow users to write strings in `[H]H:[M]M:[S]S[.DDDDDD|.F]` format to TIME.

2023-07-14 12:17 UTC, vishalkarve15 commented
/gcbrun

2023-07-14 12:19 UTC, vishalkarve15 commented
/gcbrun

2023-07-14 12:20 UTC, vishalkarve15 commented
/gcbrun

2023-07-19 09:08 UTC, vishalkarve15 commented
/gcbrun

2023-08-02 06:57 UTC, davidrabinowitz requested changes
What happens when a user reads a BQ table and then tries to write the DataFrame to another table? 

Also, please add a section to `README-template.md` explaining this option to the users

2023-08-07 05:13 UTC, vishalkarve15 commented
> What happens when a user reads a BQ table and then tries to write the DataFrame to another table?
> 
> Also, please add a section to `README-template.md` explaining this option to the users

Reading a BQ table with a TIME column will create a dataframe of Long datatype.
We cannot write Long datatype back into a BQ table as TIME.

2023-08-07 05:35 UTC, vishalkarve15 commented
/gcbrun

2023-08-08 02:02 UTC, davidrabinowitz approved these changes

2023-08-08 02:22 UTC, vishalkarve15 commented
/gcbrun

2023-08-08 03:21 UTC, merged