Avoid empty partitions during DPP
GoogleCloudDataproc/spark-bigquery-connector pull request #1077
Opened 2023-10-03 16:33 UTC by vishalkarve15

2023-10-03 16:33 UTC, vishalkarve15 commented
/gcbrun

2023-10-03 17:01 UTC, vishalkarve15 commented
/gcbrun

2023-10-04 16:58 UTC, davidrabinowitz requested changes

2023-10-06 04:49 UTC, vishalkarve15 commented on spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderContext.java
> +      return null;
Yes it's possible. Let me do that.

2023-10-06 04:55 UTC, vishalkarve15 commented
/gcbrun

2023-10-10 16:19 UTC, davidrabinowitz approved these changes

2023-10-10 16:25 UTC, merged