Enable read-session caching by default for faster Spark planning
GoogleCloudDataproc/spark-bigquery-connector pull request #1109
Opened 2023-10-27 07:13 UTC by vishalkarve15

2023-10-27 07:14 UTC, vishalkarve15 commented
/gcbrun

2023-10-27 08:00 UTC, vishalkarve15 commented
/gcbrun

2023-10-27 17:21 UTC, anoopj approved these changes

2023-10-27 17:21 UTC, anoopj commented on README.md
> +     <td>Boolean config to disable read-session caching. Caches BigQuery read-sessions to allow for faster Spark query planning.
s/read-sessions/read sessions/?

2023-10-27 18:18 UTC, vishalkarve15 commented
/gcbrun

2023-10-27 21:10 UTC, davidrabinowitz requested changes

2023-10-27 21:10 UTC, davidrabinowitz commented on CHANGES.md
> +* Enable read session caching by default for faster Spark planning
Please change to `PR #1109:  Enable read session caching by default for faster Spark planning` and place after line 8 (to keep the PRs ordered)

2023-10-27 21:10 UTC, davidrabinowitz commented on README.md
> +  <tr>
Please remove - as this is the first documentation of the flag it should appear in README-template.md only (also,  it's current default vale is `false`)

2023-10-31 05:09 UTC, vishalkarve15 commented
/gcbrun

2023-10-31 17:56 UTC, davidrabinowitz approved these changes

2023-10-31 17:56 UTC, merged