Adding config to add partner attribution
GoogleCloudDataproc/spark-bigquery-connector pull request #1187
Opened 2024-02-16 22:13 UTC by isha97

2024-02-16 23:01 UTC, davidrabinowitz requested changes
The change should be in `getUserAgent()` as well, as `(GPN:<partner>)` if such exists

2024-02-16 23:01 UTC, davidrabinowitz commented on spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConnectorUserAgentProvider.java
> +    partner.ifPresent(s -> jsonObject.addProperty("partner", s));
replace partner with `GPN`

2024-02-21 23:28 UTC, isha97 commented on spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java
> +    assertThat(config.getpartner().get()).isEqualTo("GPN:testUser");
Fixed

2024-02-21 23:28 UTC, isha97 commented on spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConnectorUserAgentProvider.java
> +    partner.ifPresent(s -> jsonObject.addProperty("partner", s));
Done

2024-02-21 23:28 UTC, isha97 commented
/gcbrun

2024-02-22 17:31 UTC, isha97 commented
/gcbrun

2024-02-27 18:48 UTC, isha97 commented
/gcbrun

2024-02-27 18:56 UTC, davidrabinowitz approved these changes

2024-02-27 20:59 UTC, merged