Issue #1254: fix getting partitioning fields for pseudo columns
GoogleCloudDataproc/spark-bigquery-connector pull request #1258
Opened 2024-07-12 13:38 UTC by vishalkarve15

When getting partitioning fields, `timePartitioning.getField()` returns null when the table is ingestion time partitioned (partitioned by `_PARTITIONTIME` OR `_PARTITIONDATE`).
The change fixes this bug.

2024-07-12 13:39 UTC, vishalkarve15 commented
/gcbrun

2024-07-12 16:45 UTC, davidrabinowitz requested changes
Can you please add an integration test based on issue #1254 ?

2024-07-15 13:42 UTC, vishalkarve15 commented
/gcbrun

2024-07-15 13:43 UTC, vishalkarve15 commented
Added integration tests which fail as expected without the fix.

2024-07-15 15:51 UTC, davidrabinowitz requested changes

2024-07-15 15:51 UTC, davidrabinowitz commented on spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/ReadIntegrationTestBase.java
> +  @Test
Please add some data into the tables, and we need to heave at least one assert. Also, as this refers to ingestion time partitioning, then the partition date should be taken from the test date (dynamically), or to push data into a specific partition using table decorators.

2024-07-16 12:33 UTC, vishalkarve15 commented
/gcbrun

2024-07-16 12:56 UTC, vishalkarve15 commented
/gcbrun

2024-07-29 17:14 UTC, isha97 approved these changes

2024-07-30 04:00 UTC, merged