Encode snapshotTimeMillis in view materialization query
GoogleCloudDataproc/spark-bigquery-connector pull request #1259
Opened 2024-07-12 16:58 UTC by tom-s-powell

`snapshotTimeMillis` does not currently make sense with views since the view is materialized to a table without taking this property into consideration, and then a read session is created attempting to read the materialized table at this timestamp (which has only just been created). This change will instead use `snapshotTimeMillis` to add `FOR SYSTEM_TIME AS OF TIMESTAMP_MILLIS` clause to the query that materializes the view to a table and the read session simply consumes that.

2024-07-19 20:55 UTC, isha97 requested changes

2024-07-19 20:55 UTC, isha97 commented on bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorTest.java
> +import com.google.cloud.bigquery.*;
nit : please expand all imports

2024-07-19 20:56 UTC, isha97 commented
/gcbrun

2024-07-22 09:57 UTC, tom-s-powell commented on bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorTest.java
> +import com.google.cloud.bigquery.*;
Fixed

2024-07-22 16:46 UTC, isha97 approved these changes

2024-07-22 16:46 UTC, isha97 commented
/gcbrun

2024-07-22 19:25 UTC, merged