fixed issue with the read filter in case of nested AND and OR for AVRO readformat
GoogleCloudDataproc/spark-bigquery-connector pull request #347
Opened 2021-03-23 16:34 UTC by himanshukohli09

2021-03-23 17:13 UTC, himanshukohli09 commented
/gcbrun

2021-03-24 09:44 UTC, himanshukohli09 commented
/gcbrun

2021-03-25 04:28 UTC, davidrabinowitz requested changes

2021-03-25 04:28 UTC, davidrabinowitz commented on connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
> +        "(((((`c1` >= 500) AND (`c2` <= 300))) OR (((`c1` <= 800) " + "AND (`c3` >= 230)))))",
Please remove the string concatenation

2021-03-25 14:01 UTC, himanshukohli09 commented on connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
> +        "(((((`c1` >= 500) AND (`c2` <= 300))) OR (((`c1` <= 800) " + "AND (`c3` >= 230)))))",
Done

2021-03-25 14:14 UTC, himanshukohli09 commented
/gcbrun

2021-03-25 15:44 UTC, davidrabinowitz approved these changes

2021-03-25 15:44 UTC, merged