Add a utility class for parallel reading from ArrowStreams
GoogleCloudDataproc/spark-bigquery-connector pull request #373
Opened 2021-04-23 19:00 UTC by emkornfield

I'll incorporate this into the actual Arrow flow in a separate PR.

2021-04-23 19:00 UTC, emkornfield commented
/gcbrun

2021-04-23 19:15 UTC, emkornfield commented
/gcbrun

2021-04-23 22:06 UTC, emkornfield commented
/gcbrun

2021-04-23 22:16 UTC, emkornfield commented
/gcbrun

2021-04-27 23:42 UTC, davidrabinowitz requested changes

2021-04-29 03:59 UTC, emkornfield commented on connector/src/main/java/com/google/cloud/bigquery/connector/common/ParallelArrowReader.java
> +                      readException = new IOException(e);
done.

2021-04-29 03:59 UTC, emkornfield commented
/gcbrun

2021-05-14 17:12 UTC, davidrabinowitz approved these changes

2021-05-14 17:13 UTC, merged