Changed readme to address that source and destnation tables should be…
GoogleCloudDataproc/spark-bigquery-connector pull request #381
Opened 2021-04-28 18:22 UTC by himanshukohli09

… in same location while reading from query and views.

Also, clarified the usage of project and dataset options.

2021-04-28 18:23 UTC, himanshukohli09 commented
/gcbrun

2021-04-28 23:15 UTC, davidrabinowitz requested changes

2021-04-28 23:15 UTC, davidrabinowitz commented on README.md
> +**Note:** As mentioned [here](https://cloud.google.com/bigquery/docs/writing-results#temporary_and_permanent_tables),
"here" -> "in the BigQuery documentation"

2021-04-28 23:15 UTC, davidrabinowitz commented on README.md
> +`[project]:[dataset].[table]`.
`[project]:[dataset].[table]` -> `[project].[dataset].[table]`

2021-04-28 23:15 UTC, davidrabinowitz commented on README.md
> +   <td>The dataset containing the table. This option is intended to be used only
This option should be used with standard table and views, but not when loading query results

2021-04-28 23:15 UTC, davidrabinowitz commented on README.md
> +   <td>The Google Cloud Project ID of the table. This option is intended to be
This option should be used with standard table and views, but not when loading query results

2021-04-29 14:58 UTC, himanshukohli09 commented
/gcbrun

2021-04-29 15:06 UTC, himanshukohli09 reviewed
resolved comments

2021-04-30 20:15 UTC, himanshukohli09 commented
/gcbrun

2021-09-17 23:53 UTC, davidrabinowitz approved these changes

2021-09-17 23:54 UTC, merged