Push all filters to BigQuery Storage API
GoogleCloudDataproc/spark-bigquery-connector pull request #413
Opened 2021-06-11 22:03 UTC by esert-g

This PR modifies the filter handling code so that connector pushes all the filters it is handed by spark to the BigQuery Storage API for the read case. There is still an option to disable this (set `pushAllFilters` to `False`) so if spark tries to pushes something Storage API can't handle, users can turn this feature off.

2021-06-11 22:41 UTC, davidrabinowitz commented
/gcbrun

2021-06-11 22:55 UTC, davidrabinowitz requested changes
For `SparkFilterUtilsTest` - as there are 3 use case (AVRO/true, AVRO/false, ARROW/true) it would be better to move those tests into a new **parameterized** test class. It will also remove the multiple tests in a single unit-test anti-pattern

2021-06-11 22:55 UTC, davidrabinowitz commented on connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
> +  public void setPushAllFilters(boolean pushAllFilters) {
The class has no setter methods, please remove

2021-06-11 22:55 UTC, davidrabinowitz commented on connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
> +    filters.filter(filter => DirectBigQueryRelation.isTopLevelFieldFilterHandled(options.getPushAllFilters,
nit: Please move the new parameter to the next line

2021-06-11 22:55 UTC, davidrabinowitz commented on connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
> +        isFilterWithNamedFieldHandled(filter, readDataFormat, fields, attr)
Why the Java implementation propagates `pushAllFilters` and the scala one doesn't?

2021-06-11 22:55 UTC, davidrabinowitz commented on connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
> +        if (dataFormat == ARROW && !pushAllFilters) {
Please document

2021-06-11 22:55 UTC, davidrabinowitz commented on connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
> +        if (dataFormat == ARROW && !pushAllFilters) {
Please document

2021-06-11 22:55 UTC, davidrabinowitz commented on connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
> +        if (dataFormat == ARROW && !pushAllFilters) {
Please document

2021-06-11 22:55 UTC, davidrabinowitz commented on connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
> +      for (DataFormat dataFormat : dataFormatArgs) {
same

2021-06-14 20:21 UTC, esert-g reviewed
Converted SparkFilterUtilsTest.java to parameterized test.

2021-06-14 20:21 UTC, esert-g commented on connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
> +        if (dataFormat == ARROW && !pushAllFilters) {
Done.

2021-06-14 20:21 UTC, esert-g commented on connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
> +        if (dataFormat == ARROW && !pushAllFilters) {
Done.

2021-06-14 20:21 UTC, esert-g commented on connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
> +        if (dataFormat == ARROW && !pushAllFilters) {
Done.

2021-06-14 20:21 UTC, esert-g commented on connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
> +      for (DataFormat dataFormat : dataFormatArgs) {
Done.

2021-06-21 05:10 UTC, davidrabinowitz commented
/gcbrun

2021-06-21 16:28 UTC, davidrabinowitz approved these changes

2021-06-21 16:28 UTC, merged