Update google-cloud-bigquerystorage dependency to 2.1.2
GoogleCloudDataproc/spark-bigquery-connector pull request #456
Opened 2021-09-10 00:51 UTC by esert-g

This version includes necessary changes to handle certain
RESOURCE_EXHAUSTED errors returned from Bigquery sStorage Read
service.

2021-09-10 00:52 UTC, esert-g commented
/gcbrun

2021-09-13 20:39 UTC, davidrabinowitz commented
Hi @esert-g , this PR should be in the [branch-0.22](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/tree/branch-0.22) branch. The master has moved to maven, and the relevant BOM should be set in the [spark-bigqeury-parent POM file](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-parent/pom.xml).

2021-09-13 23:53 UTC, davidrabinowitz requested changes
Hi @esert-g , this PR should be in the [branch-0.22](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/tree/branch-0.22) branch. The master has moved to maven, and the relevant BOM should be set in the [spark-bigqeury-parent POM file](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-parent/pom.xml).

2021-09-14 19:52 UTC, esert-g commented
> Hi @esert-g , this PR should be in the [branch-0.22](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/tree/branch-0.22) branch. The master has moved to maven, and the relevant BOM should be set in the [spark-bigqeury-parent POM file](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-parent/pom.xml).

Hi @davidrabinowitz I updated the PR so now it only changes the google-cloud-bom version.

2021-09-14 20:16 UTC, davidrabinowitz commented
/gcbrun

2021-09-14 21:20 UTC, davidrabinowitz approved these changes

2021-09-14 21:22 UTC, merged