Spark DataSource V2 Write with "BigQuery Storage Write API"
GoogleCloudDataproc/spark-bigquery-connector pull request #469
Opened 2021-10-02 00:26 UTC by himanshukohli09

2021-10-02 00:27 UTC, himanshukohli09 commented
/gcbrun

2021-10-02 01:43 UTC, himanshukohli09 commented
/gcbrun

2021-10-04 00:14 UTC, himanshukohli09 commented
/gcbrun

2021-11-09 19:35 UTC, himanshukohli09 commented on spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java
> +    Assert.assertThrows(
Done

2021-11-09 19:36 UTC, himanshukohli09 commented on spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java
> +        Exception.class,
Its tricky! V1 and V2 throws different exceptions. V1 throws IllegalArgumentException and V2 throws ProvisionException as the code breaks at guice.

2021-11-09 19:36 UTC, himanshukohli09 commented on spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java
> +    if (isDirectWrite) {
Done

2021-11-09 19:36 UTC, himanshukohli09 commented on spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java
> +    if (isDirectWrite) {
Done

2021-11-09 19:36 UTC, himanshukohli09 commented on spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java
> +    if (isDirectWrite) {
Done

2021-11-09 19:36 UTC, himanshukohli09 commented on spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java
> +    if (isDirectWrite) {
Done

2021-11-09 19:39 UTC, himanshukohli09 commented on spark-bigquery-dsv2/spark-bigquery-spark24/src/test/java/com/google/cloud/spark/bigquery/integration/Spark24WriteIntegrationTest.java
> +  static String fullTableName(TableId tableId) {
The method in super is different than this.

2021-11-09 20:11 UTC, himanshukohli09 commented
/gcbrun

2021-11-09 22:08 UTC, himanshukohli09 commented
/gcbrun

2021-11-10 02:53 UTC, himanshukohli09 commented on spark-bigquery-dsv2/spark-bigquery-spark24/src/test/java/com/google/cloud/spark/bigquery/integration/Spark24WriteIntegrationTest.java
> +    super(true);
Done

2021-11-10 03:01 UTC, himanshukohli09 commented
/gcbrun

2021-11-10 21:47 UTC, davidrabinowitz requested changes

2021-11-10 21:47 UTC, davidrabinowitz commented on spark-bigquery-dsv2/spark-bigquery-spark24/src/test/java/com/google/cloud/spark/bigquery/integration/Spark24WriteIntegrationTest.java
> +  static String fullTableName(TableId tableId) {
It exists in BigQueryClient. make it public static.

2021-11-11 07:04 UTC, himanshukohli09 commented on spark-bigquery-dsv2/spark-bigquery-spark24/src/test/java/com/google/cloud/spark/bigquery/integration/Spark24WriteIntegrationTest.java
> +  static String fullTableName(TableId tableId) {
Done!

2021-11-11 07:04 UTC, himanshukohli09 commented
/gcbrun

2021-11-12 16:08 UTC, davidrabinowitz approved these changes

2021-11-14 22:41 UTC, himanshukohli09 commented
/gcbrun

2021-11-15 08:43 UTC, merged