3.x Implementation of spark bigquery connector with common library
GoogleCloudDataproc/spark-bigquery-connector pull request #493
Opened 2021-11-16 05:45 UTC by BhagyaaShreeS

Modules to be considered: spark-bigquery-dsv2/spark-bigquery-dsv2-common; spark-bigquery-dsv2/spark-bigquery-spark3

2021-11-16 17:53 UTC, davidrabinowitz commented
/gcbrun

2021-11-16 19:58 UTC, davidrabinowitz requested changes
* Needs to be rebased on current master
* CLAs need to be signed by all committers
* Please remove the spark3 implementation
* The spark 2.4 implementation should be shell wrapping the common code, it should not contain extra logic

Does not compile:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/davidrab/dev/workspaces/dataproc/spark-bigquery-connector-maven/spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/common/GenericBigQueryDataSourceReader.java:[279,5] cannot find symbol
  symbol:   class List
  location: class com.google.cloud.spark.bigquery.common.GenericBigQueryDataSourceReader
[ERROR] /Users/davidrab/dev/workspaces/dataproc/spark-bigquery-connector-maven/spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/common/GenericBigQueryDataSourceReader.java:[279,39] cannot find symbol
  symbol:   class ArrayList
  location: class com.google.cloud.spark.bigquery.common.GenericBigQueryDataSourceReader
[ERROR] /Users/davidrab/dev/workspaces/dataproc/spark-bigquery-connector-maven/spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/common/GenericBigQueryDataSourceReader.java:[280,5] cannot find symbol
  symbol:   class List
  location: class com.google.cloud.spark.bigquery.common.GenericBigQueryDataSourceReader
[ERROR] /Users/davidrab/dev/workspaces/dataproc/spark-bigquery-connector-maven/spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/common/GenericBigQueryDataSourceReader.java:[280,41] cannot find symbol
  symbol:   class ArrayList
  location: class com.google.cloud.spark.bigquery.common.GenericBigQueryDataSourceReader
```

2021-11-16 19:58 UTC, davidrabinowitz commented on spark-bigquery-dsv2/spark-bigquery-spark24/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryIndirectDataSourceWriter.java
> +public class BigQueryIndirectDataSourceWriter implements DataSourceWriter, Serializable {
Why it needs to be Serializable?

2021-11-16 19:58 UTC, davidrabinowitz commented on spark-bigquery-dsv2/spark-bigquery-spark24/src/test/java/com/google/cloud/spark/bigquery/v2/JavaShakespeare.java
> +public class JavaShakespeare {
Please delete this class

2021-11-16 19:58 UTC, davidrabinowitz commented on spark-bigquery-dsv2/spark-bigquery-spark24/src/test/java/com/google/cloud/spark/bigquery/v2/WriteTest.java
> +public class WriteTest {
Please use integration tests instead

2021-11-17 04:16 UTC, davidrabinowitz requested changes
Please make sure that all files have the license header

2021-11-17 05:19 UTC, BhagyaaShreeS commented on spark-bigquery-dsv2/spark-bigquery-dsv2-common/pom.xml
> +    <licenses>
Sure, David. I will have it removed.

2021-11-17 05:19 UTC, BhagyaaShreeS commented on spark-bigquery-dsv2/spark-bigquery-dsv2-common/pom.xml
> +    <name>DSV2 BigQuery Connector Common Library</name>
I will modify the name

2021-11-17 05:19 UTC, BhagyaaShreeS commented on spark-bigquery-dsv2/spark-bigquery-dsv2-common/pom.xml
> +            <scope>compile</scope>
I will have it removed, David.

2021-11-17 05:20 UTC, BhagyaaShreeS commented on spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/common/GenericBQDataSourceReaderHelper.java
> +public class GenericBQDataSourceReaderHelper implements Serializable {
I will refactor the name everywhere

2021-11-17 05:20 UTC, BhagyaaShreeS commented on spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/common/GenericBQDataSourceReaderHelper.java
> +  public boolean isBatchReadEnable() {
I will have it refactored David

2022-01-05 20:33 UTC, closed without merging