Implemented reusing of BigQueryReadClient and BigQueryWriteClient instances
GoogleCloudDataproc/spark-bigquery-connector pull request #495
Opened 2021-11-23 07:09 UTC by VinayLondhe14

2021-11-23 07:09 UTC, VinayLondhe14 commented
/gcbrun

2021-11-23 07:32 UTC, VinayLondhe14 commented
/gcbrun

2021-11-23 08:16 UTC, VinayLondhe14 commented
/gcbrun

2021-11-23 20:11 UTC, VinayLondhe14 commented
/gcbrun

2021-11-23 20:22 UTC, emkornfield commented
Can you run some benchmarks (tpc-h/tpc-ds) to see if this impacts perf (and share internally)?

2021-11-24 19:18 UTC, davidrabinowitz requested changes

2021-11-30 02:15 UTC, VinayLondhe14 commented
/gcbrun

2021-12-01 00:28 UTC, VinayLondhe14 commented
/gcbrun

2021-12-01 01:20 UTC, VinayLondhe14 commented
/gcbrun

2021-12-01 01:30 UTC, VinayLondhe14 commented
/gcbrun

2021-12-02 01:46 UTC, VinayLondhe14 commented
/gcbrun

2021-12-02 19:35 UTC, VinayLondhe14 commented
/gcbrun

2021-12-06 16:59 UTC, davidrabinowitz requested changes

2021-12-06 16:59 UTC, davidrabinowitz commented on bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactory.java
> +    if (credentials instanceof ExternalAccountCredentials) {
`hashCode()` input should be the same as `equals()`, so please create a hashCode for `ExternalAccountCredentials` as well. Th e best is to move all credentials handling code (including the equals related methods below) to an independent utility class - none of this functionality is unique to `BigQueryClientFactory`

2021-12-06 16:59 UTC, davidrabinowitz commented on bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactory.java
> +      ByteArrayOutputStream byteArrayOutputStream2 = new ByteArrayOutputStream();
Duplicated code, lines 191-194, 196-199 can be extracted to another method returning `byte[]` (which can also be used by `hashCode()`, see above)

2021-12-06 20:26 UTC, VinayLondhe14 commented
/gcbrun

2021-12-06 23:07 UTC, davidrabinowitz approved these changes

2021-12-06 23:13 UTC, merged