Added field level schema check in indirect mode and an option to ignoring the mode, during field comparison
GoogleCloudDataproc/spark-bigquery-connector pull request #613
Opened 2022-05-05 05:11 UTC by suryasoma

Added field level schema check in indirect mode while writing data to BigQuery and an option (enableModeCheckForSchemaFields) to ignoring the mode, during field comparison

2022-05-05 05:12 UTC, suryasoma commented
/gcburn

2022-05-05 15:27 UTC, davidrabinowitz commented on bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
>      if (f1 == f2) {
Not relevant

2022-05-05 15:29 UTC, davidrabinowitz requested changes

2022-05-05 15:29 UTC, davidrabinowitz commented on README.md
> +   <tr valign="top">
This should be added to README-template.md, not the README it self (the template was added yesterday. Please rebase the branch)

2022-05-05 17:40 UTC, suryasoma commented
/gcburn

2022-05-05 18:33 UTC, davidrabinowitz commented on bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
>      if (f1 == f2) {
ignore

2022-05-05 19:09 UTC, suryasoma commented
/gcburn

2022-05-05 19:22 UTC, VinayLondhe14 commented
/gcbrun

2022-05-05 19:32 UTC, davidrabinowitz approved these changes

2022-05-05 19:33 UTC, davidrabinowitz commented
/gcbrun

2022-05-05 19:39 UTC, davidrabinowitz requested changes
Please commit after running `./mvnw -Pall spotless:apply`

2022-05-05 22:13 UTC, davidrabinowitz commented
/gcbrun

2022-05-05 23:59 UTC, davidrabinowitz commented
/gcbrun

2022-05-06 00:11 UTC, suryasoma commented
/gcbrun

2022-05-06 00:18 UTC, davidrabinowitz commented on bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
>      if (fl1 == fl2) {
ignore

2022-05-06 00:18 UTC, davidrabinowitz commented on bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
>      if (s1 == s2) {
ignore

2022-05-06 00:19 UTC, davidrabinowitz commented on bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
>      if (f1 == f2) {
@sonatype-lift ignore

2022-05-09 05:01 UTC, suryasoma commented
/gcbrun

2022-05-10 19:43 UTC, suryasoma commented
/gcbrun

2022-05-10 19:57 UTC, suryasoma commented
/gcbrun

2022-05-11 19:05 UTC, VinayLondhe14 approved these changes
Left a minor comment but feel free to merge after addressing it

2022-05-11 19:49 UTC, suryasoma commented on bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
> +              sourceTableSchema, /* regardFieldOrder */
updated

2022-05-11 19:49 UTC, suryasoma commented on spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java
> +  public void testIndirectWriteToBigQueryWithDiffInSchemaNullableFieldAndDisableModeCheckk() {
updated

2022-05-11 19:51 UTC, merged