Implemented functionality to ensure sorted results are returned when df.show() is called
GoogleCloudDataproc/spark-bigquery-connector pull request #757
Opened 2022-08-31 17:40 UTC by VinayLondhe14

2022-08-31 17:40 UTC, VinayLondhe14 commented
/gcbrun

2022-08-31 19:45 UTC, VinayLondhe14 commented
/gcbrun

2022-08-31 19:55 UTC, VinayLondhe14 commented
/gcbrun

2022-08-31 20:18 UTC, VinayLondhe14 commented
/gcbrun

2022-08-31 21:08 UTC, VinayLondhe14 commented
/gcbrun

2022-08-31 22:06 UTC, davidrabinowitz requested changes
Please add the changes to spark 3.2/3.3 as well

2022-08-31 22:07 UTC, davidrabinowitz commented
Also, please rebase from master

2022-09-01 15:58 UTC, VinayLondhe14 commented
I'll split this PR into multiple PRs

2022-09-01 15:58 UTC, closed without merging