json related changes #804
GoogleCloudDataproc/spark-bigquery-connector pull request #805
Opened 2022-10-15 17:58 UTC by abhijeet-lele

2022-10-16 18:42 UTC, abhijeet-lele commented
Identified an issue with Spark cache will fix it.

2022-11-29 00:41 UTC, davidrabinowitz commented
/gcbrun

2022-11-29 01:44 UTC, davidrabinowitz requested changes

2022-12-07 23:03 UTC, davidrabinowitz approved these changes

2022-12-07 23:03 UTC, merged