Creating BigQueryReadClient with UnboundedScheduledExecutorService
GoogleCloudDataproc/spark-bigquery-connector pull request #951
Opened 2023-04-17 21:38 UTC by suryasoma

Updating the default ExecutorProvider

2023-04-17 21:38 UTC, suryasoma commented
/gcbrun

2023-04-18 17:06 UTC, suryasoma commented
/gcbrun

2023-04-19 16:57 UTC, davidrabinowitz requested changes

2023-04-19 16:57 UTC, davidrabinowitz commented on bigquery-connector-common/pom.xml
> +      <version>2.43.0</version>
This version has [2 CVEs](https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-core/2.43.0), latest (2.46.0) is ok.

Also, the jar is 5MB, do we need it all for just one class? As an alternative - perhaps we can trim the redundant classes using the filter option in the shade plugin

2023-04-24 23:21 UTC, suryasoma commented
/gcbrun

2023-04-25 17:04 UTC, suryasoma commented
/gcbrun

2023-04-26 22:05 UTC, suryasoma commented
/gcbrun

2023-04-26 23:44 UTC, suryasoma commented
/gcbrun

2023-04-26 23:44 UTC, suryasoma commented on bigquery-connector-common/pom.xml
> +      <scope>provided</scope>
`spark-bigquery-parent` doesn't have ` <artifactId>annotations</artifactId>`

2023-05-01 15:30 UTC, davidrabinowitz approved these changes

2023-05-01 15:32 UTC, davidrabinowitz requested changes
Unit test is missing

2023-05-02 21:13 UTC, davidrabinowitz commented
/gcbrun

2023-05-02 21:14 UTC, davidrabinowitz approved these changes

2023-05-02 21:15 UTC, merged